apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-game2048
  namespace: game2048
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: manual
  capacity:
    storage: 10Mi
  hostPath:
    path: ${PWD}/pv-game2048
