apiVersion: v1
kind: Service
metadata:
  namespace: {{ include "game2048.name" . }}
  name: {{ .Values.service.name }}
  labels:
    {{- include "game2048.labels" . | nindent 4 }}
spec:
{{- if .Values.ingress.enabled }}
  type: ClusterIP
{{- else }}
  type: NodePort
{{- end}}
  selector:
    {{- include "game2048.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
