apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: game2048
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://hub.docker.com/r/fengfeifei/2048:v4
    path: part3/game2048
  destination:
    server: "https://kubernetes.default.svc"
    namespace: game2048
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
