apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-game2048
  namespace: game2048
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: manual
  resources:
    requests:
      storage: 10Mi
  volumeName: pv-game2048
