apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: game2048
  name: deployment2048
spec:
  selector:
    matchLabels:
      app: app2048
  replicas: 2
  template:
    metadata:
      labels:
        app: app2048
    spec:
      containers:
      - image: public.ecr.aws/l6m2t8p7/docker-2048:latest
        imagePullPolicy: IfNotPresent
        name: app2048
        ports:
        - containerPort: 80
