apiVersion: v1
kind: Service
metadata:
  namespace: game2048
  name: service2048
  labels:
    app: app2048
spec:
  #  type: NodePort
  selector:
    app: app2048
  ports:
    - port: 80
      targetPort: 80
