apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: game2049
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/pipol31/project2048
    path: part2_2049/game2049
  destination:
    server: "https://kubernetes.default.svc"
    namespace: game2049
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
